<a href="https://colab.research.google.com/github/harjeet88/A_For_Algorithms/blob/master/Numpy_class_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = [1,2,3,4]

In [3]:
a_sq =  [ i*i for i in a]

In [4]:
a_sq

[1, 4, 9, 16]

In [5]:
a = np.array(a)

In [6]:
a**2

array([ 1,  4,  9, 16])

In [7]:
type(a)

numpy.ndarray

In [8]:
a +1

array([2, 3, 4, 5])

In [9]:
l = list(range(1000000))

In [11]:
arr = np.array(l)

In [12]:
arr

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [13]:
%timeit [ i**2 for i in l]

319 ms ± 9.81 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [15]:
%timeit arr**2

762 µs ± 105 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [16]:
arr.ndim

1

In [17]:
arr.shape

(1000000,)

In [18]:
type((3))

int

In [19]:
type((3,))

tuple

In [20]:
arr1 = np.arange(1000000)

In [21]:
%timeit arr1**2

828 µs ± 82.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [22]:
np.arange(3,30,2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])