<a href="https://colab.research.google.com/github/harjeet88/A_For_Algorithms/blob/master/Numpy_class_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = [1,2,3,4]

In [3]:
a_sq =  [ i*i for i in a]

In [4]:
a_sq

[1, 4, 9, 16]

In [5]:
a = np.array(a)

In [6]:
a**2

array([ 1,  4,  9, 16])

In [7]:
type(a)

numpy.ndarray

In [8]:
a +1

array([2, 3, 4, 5])

In [9]:
l = list(range(1000000))

In [11]:
arr = np.array(l)

In [12]:
arr

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [13]:
%timeit [ i**2 for i in l]

319 ms ± 9.81 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [15]:
%timeit arr**2

762 µs ± 105 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [16]:
arr.ndim

1

In [17]:
arr.shape

(1000000,)

In [18]:
type((3))

int

In [19]:
type((3,))

tuple

In [20]:
arr1 = np.arange(1000000)

In [21]:
%timeit arr1**2

828 µs ± 82.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [22]:
np.arange(3,30,2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [23]:
np.arange(2, 10, 0.7)

array([2. , 2.7, 3.4, 4.1, 4.8, 5.5, 6.2, 6.9, 7.6, 8.3, 9. , 9.7])

In [24]:
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [26]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [27]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [29]:
np.linspace(1,11,20)

array([ 1.        ,  1.52631579,  2.05263158,  2.57894737,  3.10526316,
        3.63157895,  4.15789474,  4.68421053,  5.21052632,  5.73684211,
        6.26315789,  6.78947368,  7.31578947,  7.84210526,  8.36842105,
        8.89473684,  9.42105263,  9.94736842, 10.47368421, 11.        ])

In [32]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])